#ifdef DEBUG
const String debug_html_content = "<head><script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script><script "
                                  "src=\"debug_script.js\"></script></head><body><input id=\"i\"><textarea id=\"o\" "
                                  "style=\"width:700px;height:250px\"></textarea><button>Send</button></body>";
const String debug_script_content =
    "$(function(){var txt=\"\";var "
    "sent_request=!1;$.ajaxSetup({timeout:3000});$(\"button\").click(function(){txt=$(\"#i\").val();});function "
    "loop(){if(!sent_request){sent_request=!0;c=(txt!=\"\"?\"?c=\"+txt:\"\");txt=\"\";$.get(\"debug_update\"+c,"
    "function(data){$(\"#o\").val(data);}).always(function(){sent_request=!1;});}setTimeout(loop,2500);}loop();});";
#else
const String debug_html_content = "";
const String debug_script_content = "";
#endif

#ifdef SMALL_FACTOR
const String garden_html_content = "";
const String garden_script_content = "";

const String timer_htlm_content = "";
const String timer_script_content = "";
const String style_content = "";
#else
const String garden_html_content =
    "<html><head><meta charset=\"UTF-8\"><meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, "
    "must-revalidate\" /><meta http-equiv=\"Pragma\" content=\"no-cache\" /><meta http-equiv=\"Expires\" content=\"0\" "
    "/><script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script><link rel=\"stylesheet\" type=\"text/css\" "
    "href=\"style.css\"><script src=\"script_garden.js\"></script></head><body><div class=\"header_wrapper\"><div "
    "style=\"border-right: 2px solid grey;\"><a style=\"text-decoration:none;color:black;\" "
    "href=\"timer\">Timer</a></div><div style=\"background: lightgrey;\"><a "
    "style=\"text-decoration:none;color:black;\" href=\"gradina\">Gradina</a></div></div><div id=\"ajax_status\" "
    "style=\"text-align: right; padding: 20px 102px; margin-bottom: 20px; background-color: white;\"></div><svg "
    "preserveAspectRatio=\"xMidYMid meet\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1771 352\" "
    "width=\"100%\"><defs><radialGradient gradientTransform=\"rotate(-4,0.7578125,0.5562500953674316) "
    "translate(0,0.2646983212438123) scale(1,0.5241379310344827)\" r=\"0.62306\" cy=\"0.55625\" cx=\"0.75781\" "
    "spreadMethod=\"pad\" id=\"svg_40\"><stop offset=\"0\" stop-color=\"#c67d7b\"/><stop offset=\"1\" "
    "stop-opacity=\"0.99609\" stop-color=\"#a35f67\"/></radialGradient><linearGradient y2=\"0\" x2=\"0\" y1=\"0\" "
    "x1=\"1\" id=\"svg_42\"><stop offset=\"0\" stop-color=\"#948e8c\"/><stop offset=\"1\" "
    "stop-color=\"#6b7173\"/></linearGradient><linearGradient y2=\"0\" x2=\"0\" y1=\"1\" x1=\"0\" id=\"svg_45\"><stop "
    "offset=\"0\" stop-color=\"#bdcbd6\"/><stop offset=\"1\" stop-opacity=\"0.99219\" "
    "stop-color=\"#9ea9b2\"/></linearGradient></defs><g><title>background</title><rect fill=\"#f7ebe7\" "
    "id=\"canvas_background\" height=\"354\" width=\"1773\" y=\"-1\" x=\"-1\"/><g display=\"none\" "
    "id=\"canvasGrid\"><rect fill=\"url(#gridpattern)\" stroke-width=\"0\" y=\"0\" x=\"0\" height=\"100%\" "
    "width=\"100%\" id=\"svg_3\"/></g></g><g><title>Layer 1</title><rect id=\"svg_1\" height=\"323.99998\" "
    "width=\"61.00001\" y=\"-2.05\" x=\"1.5\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"#667856\"/><rect "
    "id=\"svg_2\" height=\"26\" width=\"553.35293\" y=\"324.95\" x=\"-1.5\" stroke-opacity=\"null\" "
    "stroke-width=\"1.5\" stroke=\"#000\" fill=\"#f7f4f4\"/><path id=\"svg_4\" "
    "d=\"m64.5,-11.04999l0.70952,335.04984l222.06274,0.00615l4.25714,-150.80642l-126.98655,0l-4.25714,-173.06608l-95."
    "78571,-0.05059l0,-11.1329z\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"url(#svg_42)\"/><rect id=\"svg_5\" height=\"74\" width=\"142\" y=\"-0.04999\" x=\"162.5\" "
    "stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"url(#svg_45)\"/><path id=\"svg_6\" "
    "d=\"m305.5,2.95001\" opacity=\"0.5\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"#c6c4fc\"/><path id=\"svg_7\" "
    "d=\"m306.60802,1.0715l-0.60802,135.40165l196.99777,0l1.21604,53.01023l126.4677,1.22506l160.5167,15.69309l57.15367,"
    "0l3.64811,-206.40153l-545.39197,1.0715z\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"url(#svg_40)\"/><rect id=\"svg_8\" height=\"82.64706\" width=\"295.11764\" y=\"271.4206\" x=\"554.85294\" "
    "stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"#bc742b\"/><line stroke-linecap=\"null\" "
    "stroke-linejoin=\"null\" id=\"svg_16\" y2=\"352.95001\" x2=\"462.5\" y1=\"326.95001\" x1=\"462.5\" "
    "fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/><line "
    "stroke-linecap=\"null\" stroke-linejoin=\"null\" id=\"svg_17\" y2=\"348.95001\" x2=\"417.5\" y1=\"323.95001\" "
    "x1=\"417.5\" fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"none\"/><line stroke-linecap=\"null\" stroke-linejoin=\"null\" id=\"svg_19\" y2=\"366.95001\" x2=\"374.5\" "
    "y1=\"324.95001\" x1=\"374.5\" fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"none\"/><line stroke-linecap=\"null\" stroke-linejoin=\"null\" id=\"svg_20\" y2=\"392.95001\" x2=\"317.5\" "
    "y1=\"324.95001\" x1=\"315.5\" fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"none\"/><rect id=\"svg_21\" height=\"174\" width=\"193\" y=\"17.23529\" x=\"874.20588\" "
    "stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"#667856\"/><rect id=\"svg_28\" "
    "height=\"181.17646\" width=\"137.11763\" y=\"11.05884\" x=\"1148.47052\" stroke-opacity=\"null\" "
    "stroke-width=\"1.5\" stroke=\"#000\" fill=\"#667856\"/><rect id=\"svg_29\" height=\"180.99999\" "
    "width=\"133.5294\" y=\"11.23529\" x=\"1298.23521\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"#667856\"/><rect id=\"svg_30\" height=\"180.82353\" width=\"127.05882\" y=\"11.41177\" x=\"1443.41168\" "
    "stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"#667856\"/><rect id=\"svg_31\" "
    "height=\"180.82351\" width=\"124.70587\" y=\"11.41177\" x=\"1585.29402\" stroke-opacity=\"null\" "
    "stroke-width=\"1.5\" stroke=\"#000\" fill=\"#667856\"/><rect id=\"svg_32\" height=\"64.70588\" "
    "width=\"923.52935\" y=\"285.70588\" x=\"849.58819\" stroke-opacity=\"null\" stroke-width=\"1.5\" stroke=\"#000\" "
    "fill=\"#bc742b\"/><line stroke-linecap=\"null\" stroke-linejoin=\"null\" id=\"svg_33\" y2=\"208.88235\" "
    "x2=\"861.38239\" y1=\"273.58823\" x1=\"843.73533\" fill-opacity=\"null\" stroke-opacity=\"null\" "
    "stroke-width=\"6.5\" stroke=\"#000\" fill=\"none\"/><line stroke-linecap=\"null\" stroke-linejoin=\"null\" "
    "id=\"svg_34\" y2=\"138.29411\" x2=\"306.08825\" y1=\"177.11764\" x1=\"284.91179\" fill-opacity=\"null\" "
    "stroke-opacity=\"null\" stroke-width=\"6.5\" stroke=\"#000\" fill=\"none\"/><rect id=\"svg_36\" "
    "height=\"52.94118\" width=\"45.88235\" y=\"139.04411\" x=\"1090.79417\" fill-opacity=\"null\" "
    "stroke-opacity=\"null\" stroke=\"#000\" fill=\"none\"/><text fill=\"#ffffff\" stroke=\"#000\" stroke-width=\"0\" "
    "stroke-opacity=\"null\" x=\"953.76418\" y=\"108.59265\" id=\"svg_9\" font-size=\"39\" font-family=\"Helvetica, "
    "Arial, sans-serif\" text-anchor=\"start\" xml:space=\"preserve\" font-weight=\"normal\">1</text><text "
    "fill=\"#ffffff\" stroke=\"#000\" stroke-width=\"0\" stroke-opacity=\"null\" fill-opacity=\"null\" y=\"108.59265\" "
    "id=\"svg_10\" font-size=\"39\" font-family=\"Helvetica, Arial, sans-serif\" text-anchor=\"start\" "
    "xml:space=\"preserve\" x=\"1202\">2</text><text fill=\"#ffffff\" stroke=\"#000\" stroke-width=\"0\" "
    "stroke-opacity=\"null\" fill-opacity=\"null\" x=\"1354\" y=\"108.59265\" id=\"svg_11\" font-size=\"39\" "
    "font-family=\"Helvetica, Arial, sans-serif\" text-anchor=\"start\" xml:space=\"preserve\">3</text><text "
    "fill=\"#ffffff\" stroke=\"#000\" stroke-width=\"0\" stroke-opacity=\"null\" fill-opacity=\"null\" x=\"1490\" "
    "y=\"108.59265\" id=\"svg_12\" font-size=\"39\" font-family=\"Helvetica, Arial, sans-serif\" text-anchor=\"start\" "
    "xml:space=\"preserve\">4</text><text fill=\"#ffffff\" stroke=\"#000\" stroke-width=\"0\" stroke-opacity=\"null\" "
    "fill-opacity=\"null\" x=\"1635\" y=\"108.59265\" id=\"svg_14\" font-size=\"39\" font-family=\"Helvetica, Arial, "
    "sans-serif\" text-anchor=\"start\" xml:space=\"preserve\">5</text><text fill=\"#ffffff\" stroke=\"#000\" "
    "stroke-width=\"0\" stroke-opacity=\"null\" fill-opacity=\"null\" x=\"25\" y=\"178.95001\" id=\"svg_15\" "
    "font-size=\"39\" font-family=\"Helvetica, Arial, sans-serif\" text-anchor=\"start\" "
    "xml:space=\"preserve\">6</text></g></svg><div class=\"page\"><div class=\"btn_wrapper\"><button class=\"btn\" "
    "id=\"garden_pause_btn\" disabled>Pauza</button></div></div><div id=\"garden_list_template\" style=\"display: "
    "none;\"><li><div style=\"display: flex;\"><div class=\"input_box\" style=\"margin-right:10px\"><input "
    "class=\"input_box_value input_schedule_start\" type=\"text\"></div><div class=\"input_box\"><input "
    "class=\"input_box_value input_schedule_end\" type=\"text\"></div></div><div class=\"list_wrapper\"><ul "
    "class=\"week_days_list\"><li>L<input type=\"checkbox\" class=\"day_state\"  data-day=\"0\"></li><li>Ma<input "
    "type=\"checkbox\" class=\"day_state\"  data-day=\"1\"></li><li>Mi<input type=\"checkbox\" class=\"day_state\"  "
    "data-day=\"2\"></li><li>J<input type=\"checkbox\" class=\"day_state\"  data-day=\"3\"></li><li>V<input "
    "type=\"checkbox\" class=\"day_state\"  data-day=\"4\"></li><li>S<input type=\"checkbox\" class=\"day_state\"  "
    "data-day=\"5\"></li><li>D<input type=\"checkbox\" class=\"day_state\"  data-day=\"6\"></li></ul></div><div "
    "class=\"list_wrapper\"><ul style=\"list-style: none;\" class=\"components_list\"><li>Zona 1 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"valve\" data-component=\"0\"></li><li>Zona 2 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"valve\" data-component=\"1\"></li><li>Zona 3 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"valve\" data-component=\"2\"></li><li>Zona 4 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"valve\" data-component=\"3\"></li><li>Zona 5 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"valve\" data-component=\"4\"></li><li>Releu 1 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"relay\" data-component=\"0\"></li><li>Releu 2 <input "
    "type=\"checkbox\" class=\"component_state\" data-type=\"relay\" "
    "data-component=\"1\"></li></ul></div></li></div><div class=\"page garden_page\"><div "
    "class=\"garden_page_content\"><div>Programari<hr></div><ol class=\"garden_schedule_list\"><li style=\"list-style: "
    "none;display:flex;justify-content: center;\" data-controls=\"true\"><div class=\"btn_wrapper\"><button "
    "class=\"btn\" id=\"garden_add_schedule\" disabled>Adauga programare</button><button class=\"btn\" "
    "id=\"garden_save\" disabled>Salveaza</button></div></li></ol></div></div></body></html>";

const String garden_script_content =
    "var initial_loaded=!1;var unsaved_data=!1;var lost_connection=!1;var garden_zones=[];var "
    "sent_refresh_request=!1;$(document).ready(function(){garden_zones=[svg_21,svg_28,svg_29,svg_30,svg_31,svg_1];"
    "lockButtonInterface(!0);$.ajaxSetup({timeout:3000});$( document "
    ").ajaxError(function(){lost_connection=!0;setAjaxError(\"\");});$(document).ajaxSuccess(function(){lost_"
    "connection=!1;clearAjaxError();});function makeRequest(){if(sent_refresh_request) return;if(initial_loaded) "
    "refreshPageData();else loadPageData();}function "
    "loop(){makeRequest();setTimeout(loop,3000);}loop();$(\"#garden_pause_btn\").click(function(){if(!initial_loaded) "
    "return;$.get(\"garden_update?mode=toggle_state\",function(){refreshPageData();});});$(\"body\").on(\"change "
    "keyup\",\"input\",function(){unsaved_data=!0;if(!lost_connection) "
    "setSaveBtnState(!0);});$(\".garden_schedule_list\").on(\"click\",\"#garden_add_schedule\",function(){if(!initial_"
    "loaded) "
    "return;$(\"#garden_list_template>li\").clone().insertBefore($(this).closest(\"li\"));unsaved_data=!0;if(!lost_"
    "connection) setSaveBtnState(!0);});$(\"#garden_save\").click(function(){if(!initial_loaded) return;var "
    "get_command=\"\";var i=0;var error=!1;$(\".garden_schedule_list > "
    "li\").each(function(el){if($(this).attr(\"data-controls\")==\"true\") return;var "
    "start=$(this).find(\".input_schedule_start\").val();var "
    "end=$(this).find(\".input_schedule_end\").val();if(start.replace(/\\s/g)==\"\" || "
    "end.replace(/\\s/g)==\"\"){$(this).remove();return;}var "
    "components=getSelectedComponents(this);if(components.selected_components.length==0){$(this).remove();return;}var "
    "week_days=getSelectedWeekDays(this);start_integer=stringTimeToInt(start);end_integer=stringTimeToInt(end);if("
    "start_integer==-1 || end_integer==-1) {alert(\"Timpii introdusi sunt malformati: \"+start+\" <-> "
    "\"+end);error=!0;return "
    "!1;}i++;get_command+=\"start[\"+i+\"]=\"+start_integer+\"&end[\"+i+\"]=\"+end_integer+\"&valve_components[\"+i+\"]"
    "=\"+components.valve_bin_components+\"&relay_components[\"+i+\"]=\"+components.relay_bin_components+\"&days[\"+i+"
    "\"]=\"+week_days.bin_days+\"&\";});if(error || i>50) {alert(\"Eroare in timpul salvarii! Nimic nu va fi "
    "salvat!\");return;}if(i==0) get_command=\"total=0\";else "
    "get_command=\"total=\"+i+\"&\"+get_command.slice(0,-1);$.get(\"garden_update?mode=set_schedule&\"+get_command,"
    "function(){refreshPageData();unsaved_data=!1;setSaveBtnState(!1);});});});function "
    "refreshPageData(initial_loading){sent_refresh_request=!0;$.get(\"garden_refresh?mode=load\",function(obj){$(\"#"
    "ajax_status\").text(obj.current_time);$(\"#garden_pause_btn\").text(obj.garden_state==1?\"Pauza\":\"Reporneste\");"
    "colorActiveZones(obj.opened_valves);}).always(function(){sent_refresh_request=!1;});}function "
    "loadPageData(){sent_refresh_request=!0;$.get(\"garden_refresh?mode=load\",function(obj){initial_loaded=!0;$(\"#"
    "garden_pause_btn\").prop(\"disabled\",!1);$(\"#garden_add_schedule\").prop(\"disabled\",!1);$(\"#ajax_status\")."
    "text(obj.current_time);$(\"#garden_pause_btn\").text(obj.garden_state==1?\"Pauza\":\"Reporneste\");for(var "
    "i=0;i<obj.schedule_list.length;i++){var "
    "el=$(\"#garden_list_template>li\").clone().insertBefore($(\"#garden_add_schedule\").closest(\"li\"));$(el).find("
    "\".components_list input[data-type='valve']\").each(function(index){$(this)[0].checked=(Math.pow(2,index) & "
    "obj.schedule_list[i].valve_components);});$(el).find(\".components_list "
    "input[data-type='relay']\").each(function(index){$(this)[0].checked=(Math.pow(2,index) & "
    "obj.schedule_list[i].relay_components);});$(el).find(\".week_days_list "
    "input\").each(function(index){$(this)[0].checked=(Math.pow(2,index) & "
    "obj.schedule_list[i].active_days);});$(el).find(\".input_schedule_start\").val(Math.floor(obj.schedule_list[i]."
    "start_time/"
    "60)+\":\"+(obj.schedule_list[i].start_time%60));$(el).find(\".input_schedule_end\").val(Math.floor(obj.schedule_"
    "list[i].end_time/"
    "60)+\":\"+(obj.schedule_list[i].end_time%60));}colorActiveZones(obj.opened_valves);}).always(function(){sent_"
    "refresh_request=!1;});}function colorActiveZones(bin){for(var i=0;i<garden_zones.length;i++){var "
    "mask=Math.pow(2,i);if(mask & bin){garden_zones[i].style.fill=\"blue\";}else "
    "garden_zones[i].style.fill=\"#667856\";}}function getSelectedWeekDays(parent_list_item){var selected_days=[];var "
    "bin_days=0;$(parent_list_item).find(\".week_days_list "
    ".day_state\").each(function(){if($(this).get(0).checked==!0){var "
    "comp_id=$(this).attr(\"data-day\");selected_days.push(comp_id);bin_days+=Math.pow(2,parseInt(comp_id));}});return "
    "{selected_days:selected_days,bin_days:bin_days};}function getSelectedComponents(parent_list_item){var "
    "selected_components=[];var valve_bin_components=0;var "
    "relay_bin_components=0;$(parent_list_item).find(\".components_list "
    ".component_state\").each(function(){if($(this).get(0).checked==!0){var "
    "comp_id=$(this).attr(\"data-component\");var "
    "comp_type=$(this).attr(\"data-type\");selected_components.push({comp_type:comp_type,comp_id:comp_id});if(comp_"
    "type==\"valve\") valve_bin_components+=Math.pow(2,parseInt(comp_id));else "
    "relay_bin_components+=Math.pow(2,parseInt(comp_id));}});return "
    "{selected_components:selected_components,valve_bin_components:valve_bin_components,relay_bin_components:relay_bin_"
    "components};}function setSaveBtnState(enable){if(enable){$(\"#garden_save\").removeAttr(\"disabled\");}else "
    "$(\"#garden_save\").attr(\"disabled\",\"\");}function "
    "lockButtonInterface(lock){$(\"#garden_save\").prop(\"disabled\",lock);if(!unsaved_data && !lock) "
    "$(\"#garden_save\").prop(\"disabled\",!0);}function "
    "setAjaxError(msg){$(\"#ajax_status\").css(\"background-color\",\"red\");lockButtonInterface(!0);}function "
    "clearAjaxError(){$(\"#ajax_status\").css(\"background-color\",\"white\");lockButtonInterface(!1);}function "
    "stringTimeToInt(str){var regex1=/^\\s*(\\d{1,2})\\s*$/g;var regex2=/^\\s*(\\d{1,2})\\s*:\\s*(\\d{1,2})\\s*$/g;var "
    "format1=regex1.exec(str);var format2=regex2.exec(str);if(format1==null && format2==null) return "
    "-1;if(format1!=null) return parseInt(format1[1]*60);return parseInt(format2[1])*60+parseInt(format2[2]);}";

const String timer_htlm_content =
    "<html><head><meta charset=\"UTF-8\"><meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, "
    "must-revalidate\" /><meta http-equiv=\"Pragma\" content=\"no-cache\" /><meta http-equiv=\"Expires\" content=\"0\" "
    "/><script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script><link rel=\"stylesheet\" type=\"text/css\" "
    "href=\"style.css\"><script src=\"script.js\"></script></head><body><div class=\"header_wrapper\"><div "
    "style=\"border-right: 2px solid grey;background: lightgrey;\"><a style=\"text-decoration:none;color:black;\" "
    "href=\"timer\">Timer</a></div><div><a style=\"text-decoration:none;color:black\" "
    "href=\"gradina\">Gradina</a></div></div><div id=\"ajax_status\" style=\"text-align: right; padding: 20px 102px; "
    "margin-bottom: 20px; background-color: white;\"></div><div class=\"page\"><div><div "
    "class=\"input_box\"><label>Cat timp sta deschis</label><input class=\"input_box_value\" id=\"timer_opened_time\" "
    "type=\"text\"></div><div class=\"input_box\"><label>Cat timp sta inchis</label><input class=\"input_box_value\" "
    "id=\"timer_closed_time\" type=\"text\"></div></div></div><div class=\"page\"><div class=\"btn_wrapper\"><button "
    "class=\"btn\" id=\"timer_update_btn\" disabled>Salveaza</button><button class=\"btn\" "
    "id=\"timer_pause_btn\">Pauza</button><button class=\"btn\" id=\"timer_start_btn\"> Porneste pentru<select "
    "id=\"timeouts\"><option value=\"2\">2</option><option value=\"5\">5</option><option value=\"7\">7</option><option "
    "value=\"10\">10</option><option value=\"12\">12</option><option value=\"15\">15</option><option "
    "value=\"20\">20</option></select> min </button></div></div><div class=\"page\" "
    "style=\"font-size:40px;\"><div>Stare curenta: <span id=\"timer_state\" class=\"highlight\">?</span>. "
    "</div><div>Cronometrul principal: <span id=\"timer_remaining\" class=\"highlight\">?</span> minute pana la <span "
    "id=\"timer_primary_next_state\" class=\"highlight\">?</span>.</div><div>Cronometrul secundar: <span "
    "id=\"timer_secondary_remaining\" class=\"highlight\">?</span> minute pana la oprire.</div></div></body></html>";

const String timer_script_content =
    "var timer_state=2;var initial_loaded=!1;var sent_refresh_request=!1;var "
    "unsaved_data=!1;$(document).ready(function(){$.ajaxSetup({timeout:3000});$(\"body\").on(\"change "
    "keyup\",\"input\",function(){unsaved_data=!0;setSaveBtnState(!0);});$(\"#timer_update_btn\").click(function(){var "
    "opened_time=parseInt($(\"#timer_opened_time\").val());var "
    "closed_time=parseInt($(\"#timer_closed_time\").val());if(opened_time>=255 || closed_time>=255){alert(\"Valori "
    "prea "
    "mari\");return;}$.get(\"timer_update?mode=time&opened_time=\"+(opened_time*60)+\"&closed_time=\"+(closed_time*60),"
    "function(){unsaved_data=!1;setSaveBtnState(!1);refreshPageData();});});$(\"#timer_start_btn\").click(function(e){"
    "if(e.target.id!==\"timer_start_btn\") return;var time=parseInt($(\"#timeouts\").val());if(timer_state==2) "
    "return;$.get(\"timer_start?time=\"+(time*60),function(){refreshPageData();});});$(\"#timer_pause_btn\").click("
    "function(){$.get(\"timer_update?mode=state_change\",function(){refreshPageData();});});$( document "
    ").ajaxError(function(){setAjaxError(\"\");});$(document).ajaxSuccess(function(){clearAjaxError();});function "
    "makeRequest(){if(sent_refresh_request) return;if(initial_loaded) refreshPageData();else loadPageData();}function "
    "loop(){makeRequest();setTimeout(loop,3000);}loop();});function "
    "loadPageData(){sent_refresh_request=!0;$.get(\"timer_refresh\",function(obj){initial_loaded=!0;$(\"#timer_state\")"
    ".text(obj.output_state==0?\"Deschis\":\"Inchis\");$(\"#ajax_status\").text(obj.current_time);$(\"#timer_opened_"
    "time\").val(Math.floor(obj.opened_time/60));$(\"#timer_closed_time\").val(Math.floor(obj.closed_time/"
    "60));$(\"#timer_remaining\").text(Math.floor(obj.remaining/"
    "60)+\":\"+(obj.remaining%60));$(\"#timer_primary_next_state\").text(obj.primary_output_state==1?\"Deschidere\":"
    "\"Inchidere\");$(\"#timer_secondary_remaining\").text(Math.floor(obj.secondary_remaining/"
    "60)+\":\"+(obj.secondary_remaining%60));timer_state=obj.timer_state;var button_text=\"\";if(obj.timer_state==0) "
    "button_text=\"Pauza\";else if(obj.timer_state==1) button_text=\"Revoca contorul\";else "
    "button_text=\"Reporneste\";$(\"#timer_pause_btn\").text(button_text);}).always(function(){sent_refresh_request=!1;"
    "});}function "
    "refreshPageData(){sent_refresh_request=!0;$.get(\"timer_refresh\",function(obj){$(\"#timer_state\").text(obj."
    "output_state==0?\"Deschis\":\"Inchis\");$(\"#ajax_status\").text(obj.current_time);$(\"#timer_remaining\").text("
    "Math.floor(obj.remaining/"
    "60)+\":\"+(obj.remaining%60));$(\"#timer_primary_next_state\").text(obj.primary_output_state==1?\"Deschidere\":"
    "\"Inchidere\");$(\"#timer_secondary_remaining\").text(Math.floor(obj.secondary_remaining/"
    "60)+\":\"+(obj.secondary_remaining%60));timer_state=obj.timer_state;var button_text=\"\";if(obj.timer_state==0) "
    "button_text=\"Pauza\";else if(obj.timer_state==1) button_text=\"Revoca contorul\";else "
    "button_text=\"Reporneste\";$(\"#timer_pause_btn\").text(button_text);}).always(function(){sent_refresh_request=!1;"
    "});}function setSaveBtnState(enable){if(enable){$(\"#timer_update_btn\").removeAttr(\"disabled\");}else "
    "$(\"#timer_update_btn\").attr(\"disabled\",\"\");}function "
    "setAjaxError(msg){$(\"#ajax_status\").css(\"background-color\",\"red\");}function "
    "clearAjaxError(){$(\"#ajax_status\").css(\"background-color\",\"white\");}";

const String style_content =
    "body{margin:0;}.header_wrapper {font-size: 35px;border-bottom: 1px solid grey;display: flex;flex-direction: "
    "row;}.header_wrapper div {display: flex;width: 100%;text-align: center;flex-direction: column;padding: 6px "
    "0;}.input_box {padding:6px 0;display: flex;justify-content: center;align-items: center;}.input_box label "
    "{margin-right: 17px;}.input_box_value {width:100px;min-height:37px;align-self:stretch;}.page {font-size: "
    "40px;display: flex;justify-content: center;flex-direction: column;align-items: center;}.btn_wrapper "
    "{display:flex;}.btn {min-height:46px;align-self:stretch;font-size: 19px;margin: 33px auto;flex-grow:1;display: "
    "flex;align-items: center;justify-content: center;min-width: 220px;}.highlight "
    "{color:red;}#timeouts{align-self:stretch;font-size:inherit;}.garden_page_content{min-width:80%;}.garden_schedule_"
    "list .input_box .input_box_value{width:70px;}.list_wrapper{font-size:24px;}.list_wrapper ul li{display: "
    "flex;align-items: center;}.list_wrapper .week_days_list{display: flex;}.list_wrapper .week_days_list "
    "li{flex:1;}.list_wrapper .component_state{margin-left: 20px;}input[type='checkbox']{transform:scale(1.3)  }@media "
    "(max-device-width: 800px){#ajax_status{font-size:50px;}.header_wrapper {font-size: 80px;}.page "
    "{font-size:80px;}input{font-size:50px;}.btn_wrapper {width:100%;}.btn{font-size:50px;height:100px;min-width: "
    "unset;}.garden_schedule_list .input_box .input_box_value{width:270px;}.list_wrapper{font-size:54px;}.list_wrapper "
    ".week_days_list li{margin-right:30px;}.list_wrapper .day_state{margin-left:20px;}.list_wrapper "
    ".component_state{margin-left: 100px;}input[type='checkbox']{transform:scale(4)  }}";
#endif
